import React, { useState } from 'react';
import { X, Sparkles, Calendar, Clock, Flame, BookOpen, FileText } from 'lucide-react';
import { CreatePlanRequest, StudyIntensity, StudyPlan } from '../types';
import { PRESET_STUDY_PLANS } from '../data/presets';

interface PlanCreatorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onPlanCreated: (plan: StudyPlan) => void;
}

export const PlanCreatorModal: React.FC<PlanCreatorModalProps> = ({
  isOpen,
  onClose,
  onPlanCreated
}) => {
  const defaultDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

  const [subject, setSubject] = useState('');
  const [deadline, setDeadline] = useState(defaultDate);
  const [dailyHours, setDailyHours] = useState(2);
  const [intensity, setIntensity] = useState<StudyIntensity>('balanced');
  const [targetGoal] = useState('Aiming for top grade / A+');
  const [topicsOrNotes, setTopicsOrNotes] = useState('');
  
  const [isLoading, setIsLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState('');
  const [error, setError] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim()) {
      setError('Please enter a subject name or exam title.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setLoadingStep('Analyzing syllabus and mapping timeline...');

    const timer1 = setTimeout(() => setLoadingStep('Drafting comprehensive Markdown study notes...'), 2500);
    const timer2 = setTimeout(() => setLoadingStep('Crafting high-yield flashcards & quiz questions...'), 5500);
    const timer3 = setTimeout(() => setLoadingStep('Building your daily milestone schedule...'), 8500);

    try {
      const reqPayload: CreatePlanRequest = {
        subject,
        deadline,
        dailyHours,
        intensity,
        targetGoal,
        topicsOrNotes
      };

      const res = await fetch('/api/generate-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(reqPayload)
      });

      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || 'Failed to generate plan.');
      }

      const generatedData = await res.json();

      const newPlan: StudyPlan = {
        id: 'plan-' + Date.now(),
        title: `${subject} Exam Prep`,
        subject: subject,
        deadline: deadline,
        dailyHours: dailyHours,
        intensity: intensity,
        createdAt: new Date().toISOString(),
        colorTheme: generatedData.colorTheme || '#6366f1',
        summary: generatedData.summary || 'Custom study plan generated by AI.',
        motivationQuote: generatedData.motivationQuote || 'Believe you can and you are halfway there.',
        totalEstimatedHours: generatedData.totalEstimatedHours || dailyHours * 5,
        schedule: generatedData.schedule || [],
        notesMarkdown: generatedData.notesMarkdown || '# Study Notes',
        keyConcepts: generatedData.keyConcepts || [],
        flashcards: generatedData.flashcards || [],
        quiz: generatedData.quiz || [],
        cheatSheet: generatedData.cheatSheet || []
      };

      onPlanCreated(newPlan);
      onClose();
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Something went wrong while communicating with Gemini AI.');
    } finally {
      clearTimeout(timer1);
      clearTimeout(timer2);
      clearTimeout(timer3);
      setIsLoading(false);
    }
  };

  const loadPreset = (preset: StudyPlan) => {
    // Clone with fresh IDs
    const clonedPlan: StudyPlan = {
      ...preset,
      id: 'plan-preset-' + Date.now(),
      createdAt: new Date().toISOString()
    };
    onPlanCreated(clonedPlan);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-900/40 backdrop-blur-md overflow-y-auto animate-fade-in">
      <div className="relative w-full max-w-2xl bg-white border border-stone-200 rounded-3xl shadow-xl overflow-hidden my-8">
        
        {/* Header */}
        <div className="p-6 border-b border-stone-200 bg-stone-50 text-stone-900 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-[#E07A5F] flex items-center justify-center text-white shadow-xs">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-stone-900">Create AI Study Plan</h2>
              <p className="text-xs text-stone-500 font-medium">Custom schedules, notes, flashcards & quizzes for any deadline</p>
            </div>
          </div>

          <button
            onClick={onClose}
            disabled={isLoading}
            className="p-2 rounded-xl bg-stone-100 hover:bg-stone-200 text-stone-500 hover:text-stone-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 sm:p-8 space-y-6">

          {/* Quick Presets row */}
          <div>
            <label className="block text-xs font-semibold text-stone-600 uppercase tracking-wider mb-3">
              ⚡ Quick Start Presets (1-Click Load)
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {PRESET_STUDY_PLANS.map(preset => (
                <button
                  key={preset.id}
                  type="button"
                  onClick={() => loadPreset(preset)}
                  disabled={isLoading}
                  className="flex items-center justify-between p-3.5 rounded-2xl border border-stone-200 bg-stone-50 hover:border-[#E07A5F] hover:bg-amber-50/50 transition-all text-left shadow-2xs"
                >
                  <div className="flex items-center gap-3">
                    <span className="w-3.5 h-3.5 rounded-full border border-stone-300" style={{ backgroundColor: preset.colorTheme || '#E07A5F' }} />
                    <div>
                      <p className="text-xs font-bold text-stone-900">{preset.subject}</p>
                      <p className="text-[11px] font-medium text-stone-500 truncate max-w-[170px]">{preset.title}</p>
                    </div>
                  </div>
                  <span className="text-[10px] font-bold text-amber-900 bg-amber-100 px-2.5 py-1 rounded-lg border border-amber-200">
                    Use
                  </span>
                </button>
              ))}
            </div>
          </div>

          <div className="relative flex items-center justify-center">
            <div className="absolute inset-0 flex items-center"><div className="w-full border-t border-stone-200"></div></div>
            <span className="relative px-3 bg-white text-xs text-stone-400 font-semibold uppercase tracking-wider">Or Custom AI Generation</span>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-5">
            {error && (
              <div className="p-3.5 rounded-xl bg-rose-100 border border-rose-200 text-rose-900 font-medium text-xs">
                ⚠️ {error}
              </div>
            )}

            {/* Subject name */}
            <div>
              <label className="block text-xs font-semibold text-stone-700 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                <BookOpen className="w-4 h-4 text-[#E07A5F]" />
                Subject / Exam Title *
              </label>
              <input
                type="text"
                placeholder="e.g. AP Chemistry Midterm, Organic Chemistry, World History, Machine Learning"
                value={subject}
                onChange={e => setSubject(e.target.value)}
                disabled={isLoading}
                required
                className="w-full px-4 py-3 rounded-xl bg-stone-50 border border-stone-200 text-stone-900 placeholder-stone-400 focus:outline-none focus:border-[#E07A5F] text-xs font-medium shadow-2xs"
              />
            </div>

            {/* Row 2: Target Deadline & Daily Hours */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-semibold text-stone-700 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                  <Calendar className="w-4 h-4 text-[#E07A5F]" />
                  Target Exam / Deadline *
                </label>
                <input
                  type="date"
                  value={deadline}
                  onChange={e => setDeadline(e.target.value)}
                  disabled={isLoading}
                  required
                  className="w-full px-4 py-3 rounded-xl bg-stone-50 border border-stone-200 text-stone-900 focus:outline-none focus:border-[#E07A5F] text-xs font-medium shadow-2xs"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 uppercase tracking-wider mb-1.5 flex items-center justify-between">
                  <span className="flex items-center gap-1.5">
                    <Clock className="w-4 h-4 text-[#E07A5F]" />
                    Daily Hours
                  </span>
                  <span className="text-[#E07A5F] font-bold">{dailyHours} hrs/day</span>
                </label>
                <input
                  type="range"
                  min="0.5"
                  max="8"
                  step="0.5"
                  value={dailyHours}
                  onChange={e => setDailyHours(parseFloat(e.target.value))}
                  disabled={isLoading}
                  className="w-full h-2 bg-stone-100 border border-stone-200 rounded-lg appearance-none cursor-pointer accent-[#E07A5F] my-2"
                />
                <div className="flex justify-between text-[10px] font-medium text-stone-400">
                  <span>30m Light</span>
                  <span>2.5h Recommended</span>
                  <span>8h Intensive</span>
                </div>
              </div>
            </div>

            {/* Intensity Level Selection */}
            <div>
              <label className="block text-xs font-semibold text-stone-700 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                <Flame className="w-4 h-4 text-amber-600" />
                Study Pace & Intensity Mode
              </label>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                {[
                  { id: 'relaxed', label: 'Relaxed 🌿', desc: 'Steady review' },
                  { id: 'balanced', label: 'Balanced ⚖️', desc: 'Optimal pace' },
                  { id: 'intense', label: 'Intense 🔥', desc: 'Deep dive' },
                  { id: 'cram', label: 'Cram Mode ⚡', desc: 'High yield fast' }
                ].map(mode => (
                  <button
                    key={mode.id}
                    type="button"
                    onClick={() => setIntensity(mode.id as StudyIntensity)}
                    disabled={isLoading}
                    className={`p-3 rounded-xl border text-left transition-all ${
                      intensity === mode.id
                        ? 'bg-amber-100 border-[#E07A5F] text-stone-900 font-bold'
                        : 'bg-stone-50 border-stone-200 text-stone-600 hover:text-stone-900'
                    }`}
                  >
                    <p className="text-xs font-medium">{mode.label}</p>
                    <p className="text-[10px] font-normal opacity-80 mt-0.5">{mode.desc}</p>
                  </button>
                ))}
              </div>
            </div>

            {/* Syllabus or specific topics */}
            <div>
              <label className="block text-xs font-semibold text-stone-700 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                <FileText className="w-4 h-4 text-[#E07A5F]" />
                Syllabus Topics or Notes (Optional)
              </label>
              <textarea
                placeholder="e.g. Chapter 4: Photosynthesis, Chapter 5: Meiosis, Pedigree Analysis, Chi-Square Test"
                rows={3}
                value={topicsOrNotes}
                onChange={e => setTopicsOrNotes(e.target.value)}
                disabled={isLoading}
                className="w-full px-4 py-3 rounded-xl bg-stone-50 border border-stone-200 text-stone-900 placeholder-stone-400 focus:outline-none focus:border-[#E07A5F] text-xs font-normal shadow-2xs"
              />
            </div>

            {/* Loading Indicator or Submit button */}
            {isLoading ? (
              <div className="p-5 rounded-xl bg-amber-100/80 border border-amber-200 text-center space-y-3">
                <div className="inline-flex p-3 rounded-xl bg-[#E07A5F] text-white animate-pulse">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className="text-xs font-bold text-amber-900 uppercase tracking-wider">{loadingStep}</p>
                  <p className="text-[11px] text-stone-600 font-medium mt-1">Gemini AI is structuring your schedule, flashcards & quiz...</p>
                </div>
              </div>
            ) : (
              <button
                type="submit"
                className="w-full py-3.5 rounded-xl bg-[#E07A5F] hover:bg-[#d0694e] text-white font-semibold text-xs shadow-xs transition-all flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4 text-white" />
                <span>Generate Complete Study Plan</span>
              </button>
            )}
          </form>
        </div>
      </div>
    </div>
  );
};


